[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.wchusbserial*  ; Auto-detects your UTS-T01
monitor_port = /dev/cu.wchusbserial*
build_flags = 
    -D WIFI_SSID=\"${sysenv.WIFI_SSID}\"            ; Get WiFi SSID from environment variable
    -D WIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"    ; Get WiFi password from environment variable
    -D TELNET_PASSWORD=\"${sysenv.TELNET_PASSWORD}\"  ; Get Telnet password from environment variable
